{{- if .Values.applications.argoRollouts.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applications.argoRollouts.name }}
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: sa-platform-root
    course: sa-b-2026
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.applications.argoRollouts.chart.repoURL }}
    chart: {{ .Values.applications.argoRollouts.chart.chart }}
    targetRevision: {{ .Values.applications.argoRollouts.chart.targetRevision }}
    helm:
      values: |
        dashboard:
          enabled: false
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.applications.argoRollouts.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
