apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-platform-root
  namespace: argocd
  labels:
    course: sa-b-2026
    app.kubernetes.io/name: sa-platform-root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ennero/Practicas-SA-B-202302220-gitops.git
    targetRevision: main
    path: p9/app-of-apps
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
