imagePullPolicy: IfNotPresent
profile:
  name: prod
  imageRepository: mirror.gcr.io/library/nginx
  imageTag: "1.25-alpine"
  logLevel: warn
  minReplicas: 3
  maxReplicas: 6
  targetCPU: 70
  resources:
    requests: { cpu: 100m, memory: 128Mi }
    limits: { cpu: 750m, memory: 512Mi }
autoscaling:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
