apiVersion: v1
kind: Secret
metadata:
  name: p5-nats-auth
  namespace: {{ include "sa-platform.namespace" . }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "secrets.natsToken es requerido" .Values.secrets.natsToken | quote }}
