apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sa-platform.fullname" . }}-config
  namespace: {{ include "sa-platform.namespace" . }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
data:
  {{- include "sa-platform.configData" . | nindent 2 }}
