apiVersion: v1
kind: Secret
metadata:
  name: p5-nats-auth
  namespace: {{ include "sa-platform.namespace" . }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ default "${NATS_TOKEN}" (and .Values.secrets .Values.secrets.natsToken) | quote }}
