{{- $root := . -}}
{{- range $service := .Values.services }}
{{- if $service.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sa-platform.fullname" $root }}-{{ $service.name }}
  namespace: {{ include "sa-platform.namespace" $root }}
  labels:
    {{- include "sa-platform.labels" $root | nindent 4 }}
automountServiceAccountToken: false
{{- with $root.Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
