apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-auth
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_DATABASE: {{ default "app" .Values.auth.database | quote }}
  MARIADB_USER: {{ default "app" .Values.auth.username | quote }}
  MARIADB_PASSWORD: {{ default "${DB_PASSWORD}" .Values.auth.password | quote }}
  MARIADB_ROOT_PASSWORD: {{ default (default "${DB_PASSWORD}" .Values.auth.rootpassword) .Values.auth.rootPassword | quote }}
