apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-auth
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_DATABASE: {{ required "auth.database es requerido" .Values.auth.database | quote }}
  MARIADB_USER: {{ required "auth.username es requerido" .Values.auth.username | quote }}
  MARIADB_PASSWORD: {{ required "auth.password es requerido" .Values.auth.password | quote }}
  MARIADB_ROOT_PASSWORD: {{ required "auth.rootPassword es requerido" .Values.auth.rootPassword | quote }}
