apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-platform-prod
  namespace: argocd
  labels:
    environment: produccion
    course: sa-b-2026
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ennero/Practicas-SA-B-202302220-gitops.git
    targetRevision: main
    path: charts/sa-platform
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: produccion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
