apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}-headless
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    p5.sa/database: {{ include "mariadb.fullname" . }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
