fullnameOverride: ""
image:
  repository: mariadb
  tag: "11.4.5"
  pullPolicy: IfNotPresent
auth:
  database: app
  username: app
  password: ${DB_PASSWORD}
  rootpassword: ${DB_PASSWORD}
persistence:
  size: 1Gi
  storageClass: ""
resources:
  requests:
    cpu: 20m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
service:
  port: 3306
