apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-secrets-staging
  namespace: staging
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
  labels:
    app.kubernetes.io/managed-by: sealed-secrets
    environment: staging
spec:
  encryptedData:
    DB_PASSWORD: AgG3uV...encrypted-staging-database-password-payload...==
    JWT_SECRET: AgH5wX...encrypted-staging-jwt-secret-payload...==
    AES_KEY: AgI7yZ...encrypted-staging-aes-key-payload...==
    HMAC_PEPPER: AgJ9aB...encrypted-staging-hmac-pepper-payload...==
    NATS_TOKEN: AgK1cD...encrypted-staging-nats-token-payload...==
  template:
    metadata:
      name: sa-platform-runtime-secrets
      namespace: staging
    type: Opaque
