apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-secrets-prod
  namespace: produccion
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
  labels:
    app.kubernetes.io/managed-by: sealed-secrets
    environment: produccion
spec:
  encryptedData:
    DB_PASSWORD: AgB1kP...encrypted-production-database-password-payload...==
    JWT_SECRET: AgC7xL...encrypted-production-jwt-secret-payload...==
    AES_KEY: AgD9mN...encrypted-production-aes-key-payload...==
    HMAC_PEPPER: AgE2qR...encrypted-production-hmac-pepper-payload...==
    NATS_TOKEN: AgF4sT...encrypted-production-nats-token-payload...==
  template:
    metadata:
      name: sa-platform-runtime-secrets
      namespace: produccion
    type: Opaque
